### ISSUE TITLE
Celebrate stripping out all keys

### ISSUE THREAD

**Issue by viztastic** [continuationlabs/celebrate#26]
- `node` version - `6.7.0`
- `celebrate` version - `4.0.1`
- `joi` version (via `npm ls --depth=0 | grep joi`) - `10.2.0`

My `joi` schema looks like this:

```typescript
 export const JUserSchema = Joi.object().keys({
        "name"          : Joi.string().min(3).max(200).required(),
        "description"   : Joi.string().min(0).max(2000).optional()
});
```

Here is an example value that is not working as expected:

```bash
  curl -H "Content-Type: application/json" -X POST -d '{"name":"test", "description":"xyz"}' http://localhost:5000/users
```

The issue I am having with `celebrate` is:

```typescript
import { JUserSchema } from '../schemas/joi/user';
import { MUser } from '../schemas/users';
 
const Celebrate = require('celebrate');
const users = Router();

users.post('/', Celebrate({body:JUserSchema}), function(request, response, next) {
    
    MUser.create(request.body, function(error,doc) {
        if(error) response.status(500).json(error);

        response.status(200).json(doc);
    });
 });
```

Basically this goes ahead and creates an object without the `name` and `description` keys (i.e. an object with just the mongo id), even though it is a compliant object. The same happens when the object is incorrectly sent (e.g. if i remove the name key from the `POST` submission)

So there are three issues:

1. It is lettering error prone objects flow past the middleware.
2. They are getting created.
3. No proper error messaging

**Comment by arb** [comment]
Can you create a simpler example that demonstrates your problems? Preferably one that doesn't have any notion of mongoDB or multiple routers and is contained in a single file.

How are you verifying that the objects are being created? Looking at your code, it looks like this route will always respond with a 200 because even in `error` cases, you aren't returning early, so the `200` line will get called always.

As far as no proper error messaging... do you have an error handler in your router somewhere like https://github.com/continuationlabs/celebrate#celebrateerrors or something similar at the bottom of your routing table?

**Comment by cjihrig** [comment]
Ping @viztastic

**Comment by cjihrig** [comment]
No follow up. Closing.
