### ISSUE TITLE
exported Joi type definitions are missing

### ISSUE THREAD

**Issue by josalmi** [continuationlabs/celebrate#56]
- `node` version - 6.11.4
- `celebrate` version - 7.0.1
- `joi` version (via `npm ls --depth=0 | grep joi`) - 13.0.2

The issue I am having with `celebrate` is:

Type definitions for exported Joi are missing. The [`index.d.ts`](https://github.com/continuationlabs/celebrate/blob/master/lib/index.d.ts#L25) defines exported `Joi` as of type `object`. Consider defining the type as Joi from `@types/joi`.

**Comment by arb** [comment]
Eh... I'm not big into relying on 3rd party type definitions. I know we're using the express ones, but they are trivial compared to what the Joi type defs are. The lead maintainer of Joi has made it pretty clear his stance and making type defs a first party effort.

**Comment by arb** [comment]
I've had a change of heart! I'll take a PR for this, just be sure the joi types line up with the version that is actually being used by `celebrate`.

**Comment by arb** [comment]
So I was unable to find type defs for joi 12. They are available for joi 13 but this project will continue to use joi 12 for the foreseeable future. This is because express works on super old versions of node and will continue to do so. Joi 12 will be the last major release that targets node < 8.0.0. I spoke with @marsup and while 12 and 13 have the same API right now, this will likely change in the future.

**Comment by josalmi** [comment]
Thank you for looking into this.

If using Joi type defs is out of questions then maybe the type should at least be changed to `any` from `object`.

See [StackOverflow](https://stackoverflow.com/a/18961904) discussion on the differences. But simply said calling anything on now exposed `Joi` is impossible without casting it first to other type like `any` due to `object` type.

**Comment by arb** [comment]
I'd take a PR with the joi types pinned at 13.0.0. Let's try that first and see if it creates issues for anyone.
